### ISSUE TITLE
libprocessmemoryinterface.1.0.so requirement on Linux

### ISSUE THREAD

**Issue by Spongeroberto** [ThanosSiopoudis/FMScoutFramework#5]
The class ProcessMemoryAPI currently has a reference to 'libprocessmemoryinterface.1.0.so' when on Linux. Could you possibly clarify where I might find that library? It's not present on my system and a google search reveals little.

EDIT: sorry, my bad. It was missing from the archive on FMScout but I didn't check in here

**Comment by ThanosSiopoudis** [comment]
@Spongeroberto No worries. As you saw, it is a submodule linked in the folder [/ExternalLibraries/](/ThanosSiopoudis/FMScoutFramework/tree/master/ExternalLibraries)
This library still needs work, though, mainly write functions as they're missing. Feel free to modify it and send a PR.
